name: sub-hdc

services:
  mariadb:
    image: mariadb:10.6
    container_name: sub_hdc_db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: "112233"
      MARIADB_DATABASE: sub_hdc
      TZ: Asia/Bangkok
    ports:
      - "3308:3306"
    volumes:
      - sub_hdc_mariadb_data:/var/lib/mysql
      - ./table:/docker-entrypoint-initdb.d:ro
      - ./my.cnf:/etc/mysql/conf.d/custom.cnf:ro

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: sub_hdc_web
    restart: unless-stopped
    ports:
      - "80:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./webapp/.env
    environment:
      TZ: Asia/Bangkok
    command: sh -c "node lib/run_migrations.js && npm run start"
    volumes:
      - ./webapp/tmp:/app/tmp
      - ./table_update:/app/table_update:ro

volumes:
  sub_hdc_mariadb_data:
