CREATE TABLE `admission` (
  `hospcode` varchar(10) NOT NULL DEFAULT '',
  `pid` varchar(255) NOT NULL DEFAULT '',
  `seq` varchar(255) NOT NULL DEFAULT '',
  `an` varchar(255) NOT NULL DEFAULT '',
  `datetime_admit` varchar(255) NOT NULL DEFAULT '',
  `wardadmit` varchar(255) NOT NULL DEFAULT '',
  `instype` varchar(255) NOT NULL DEFAULT '',
  `typein` varchar(255) NOT NULL DEFAULT '',
  `referinhosp` varchar(255) NOT NULL DEFAULT '',
  `causein` varchar(255) NOT NULL DEFAULT '',
  `admitweight` varchar(255) NOT NULL DEFAULT '',
  `admitheight` varchar(255) NOT NULL DEFAULT '',
  `datetime_disch` varchar(255) NOT NULL DEFAULT '',
  `warddisch` varchar(255) NOT NULL DEFAULT '',
  `dischstatus` varchar(255) NOT NULL DEFAULT '',
  `dischtype` varchar(255) NOT NULL DEFAULT '',
  `referouthosp` varchar(255) NOT NULL DEFAULT '',
  `causeout` varchar(255) NOT NULL DEFAULT '',
  `cost` varchar(255) NOT NULL DEFAULT '',
  `price` varchar(255) NOT NULL DEFAULT '',
  `payprice` varchar(255) NOT NULL DEFAULT '',
  `actualpay` varchar(255) NOT NULL DEFAULT '',
  `provider` varchar(255) NOT NULL DEFAULT '',
  `d_update` varchar(255) NOT NULL DEFAULT '',
  `drg` varchar(255) NOT NULL DEFAULT '',
  `rw` varchar(255) NOT NULL DEFAULT '',
  `adjrw` varchar(255) NOT NULL DEFAULT '',
  `error` varchar(255) NOT NULL DEFAULT '',
  `warning` varchar(255) NOT NULL DEFAULT '',
  `actlos` varchar(255) NOT NULL DEFAULT '',
  `grouper_version` varchar(255) NOT NULL DEFAULT '',
  `cid` varchar(255) NOT NULL DEFAULT '',
  `cid_aes` varchar(2000) NOT NULL DEFAULT '',
  `log_import_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`hospcode`,`pid`,`an`,`datetime_disch`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
