SHOW VARIABLES LIKE '%buffer%';
SHOW VARIABLES LIKE '%innodb_log%';
SHOW VARIABLES LIKE '%innodb_flush%';
SHOW VARIABLES LIKE '%innodb_io%';
SHOW VARIABLES LIKE '%local_infile%';
SHOW VARIABLES LIKE '%unique_checks%';
SHOW VARIABLES LIKE '%autocommit%';
SHOW VARIABLES LIKE '%foreign_key_checks%';
SHOW VARIABLES LIKE '%bulk%';
