CREATE TABLE `accident` (
  `hospcode` varchar(5) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `pid` varchar(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `seq` varchar(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `datetime_serv` varchar(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `datetime_ae` varchar(255) NOT NULL DEFAULT '',
  `aetype` varchar(255) NOT NULL DEFAULT '',
  `aeplace` varchar(255) NOT NULL DEFAULT '',
  `typein_ae` varchar(255) NOT NULL DEFAULT '',
  `traffic` varchar(255) NOT NULL DEFAULT '',
  `vehicle` varchar(255) NOT NULL DEFAULT '',
  `alcohol` varchar(255) NOT NULL DEFAULT '',
  `nacrotic_drug` varchar(255) NOT NULL DEFAULT '',
  `belt` varchar(255) NOT NULL DEFAULT '',
  `helmet` varchar(255) NOT NULL DEFAULT '',
  `airway` varchar(255) NOT NULL DEFAULT '',
  `stopbleed` varchar(255) NOT NULL DEFAULT '',
  `splint` varchar(255) NOT NULL DEFAULT '',
  `fluid` varchar(255) NOT NULL DEFAULT '',
  `urgency` varchar(255) NOT NULL DEFAULT '',
  `coma_eye` varchar(255) NOT NULL DEFAULT '',
  `coma_speak` varchar(255) NOT NULL DEFAULT '',
  `coma_movement` varchar(255) NOT NULL DEFAULT '',
  `d_update` varchar(255) NOT NULL DEFAULT '',
  `cid` varchar(255) NOT NULL DEFAULT '',
  `cid_aes` varchar(2000) NOT NULL DEFAULT '',
  `log_import_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`hospcode`,`pid`,`seq`,`datetime_serv`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
