CREATE TABLE `address` (
  `hospcode` varchar(5) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `pid` varchar(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `addresstype` varchar(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `house_id` varchar(255) NOT NULL DEFAULT '',
  `housetype` varchar(255) NOT NULL DEFAULT '',
  `roomno` varchar(255) NOT NULL DEFAULT '',
  `condo` varchar(255) NOT NULL DEFAULT '',
  `houseno` varchar(1000) NOT NULL DEFAULT '',
  `soisub` varchar(255) NOT NULL DEFAULT '',
  `soimain` varchar(255) NOT NULL DEFAULT '',
  `road` varchar(255) NOT NULL DEFAULT '',
  `villaname` varchar(255) NOT NULL DEFAULT '',
  `village` varchar(255) NOT NULL DEFAULT '',
  `tambon` varchar(255) NOT NULL DEFAULT '',
  `ampur` varchar(255) NOT NULL DEFAULT '',
  `changwat` varchar(255) NOT NULL DEFAULT '',
  `d_update` varchar(255) NOT NULL DEFAULT '',
  `cid` varchar(255) NOT NULL DEFAULT '',
  `cid_aes` varchar(1000) NOT NULL DEFAULT '',
  `log_import_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`hospcode`,`pid`,`addresstype`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
