CREATE TABLE `death` (
  `hospcode` varchar(5) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `pid` varchar(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `hospdeath` varchar(255) NOT NULL DEFAULT '',
  `an` varchar(255) NOT NULL DEFAULT '',
  `seq` varchar(255) NOT NULL DEFAULT '',
  `ddeath` varchar(255) NOT NULL DEFAULT '',
  `cdeath_a` varchar(255) NOT NULL DEFAULT '',
  `cdeath_b` varchar(255) NOT NULL DEFAULT '',
  `cdeath_c` varchar(255) NOT NULL DEFAULT '',
  `cdeath_d` varchar(255) NOT NULL DEFAULT '',
  `odisease` varchar(255) NOT NULL DEFAULT '',
  `cdeath` varchar(255) NOT NULL DEFAULT '',
  `pregdeath` varchar(255) NOT NULL DEFAULT '',
  `pdeath` varchar(255) NOT NULL DEFAULT '',
  `provider` varchar(255) NOT NULL DEFAULT '',
  `d_update` varchar(255) NOT NULL DEFAULT '',
  `cid` varchar(255) NOT NULL DEFAULT '',
  `cid_aes` varchar(2000) NOT NULL DEFAULT '',
  `log_import_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`hospcode`,`pid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
