CREATE TABLE `dental` (
  `hospcode` varchar(5) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `pid` varchar(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `seq` varchar(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `date_serv` varchar(8) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `denttype` varchar(255) NOT NULL DEFAULT '',
  `servplace` varchar(255) NOT NULL DEFAULT '',
  `pteeth` varchar(255) NOT NULL DEFAULT '',
  `pcaries` varchar(255) NOT NULL DEFAULT '',
  `pfilling` varchar(255) NOT NULL DEFAULT '',
  `pextract` varchar(255) NOT NULL DEFAULT '',
  `dteeth` varchar(255) NOT NULL DEFAULT '',
  `dcaries` varchar(255) NOT NULL DEFAULT '',
  `dfilling` varchar(255) NOT NULL DEFAULT '',
  `dextract` varchar(255) NOT NULL DEFAULT '',
  `need_fluoride` varchar(255) NOT NULL DEFAULT '',
  `need_scaling` varchar(255) NOT NULL DEFAULT '',
  `need_sealant` varchar(255) NOT NULL DEFAULT '',
  `need_pfilling` varchar(255) NOT NULL DEFAULT '',
  `need_dfilling` varchar(255) NOT NULL DEFAULT '',
  `need_pextract` varchar(255) NOT NULL DEFAULT '',
  `need_dextract` varchar(255) NOT NULL DEFAULT '',
  `nprosthesis` varchar(255) NOT NULL DEFAULT '',
  `permanent_permanent` varchar(255) NOT NULL DEFAULT '',
  `permanent_prosthesis` varchar(255) NOT NULL DEFAULT '',
  `prosthesis_prosthesis` varchar(255) NOT NULL DEFAULT '',
  `gum` varchar(255) NOT NULL DEFAULT '',
  `schooltype` varchar(255) NOT NULL DEFAULT '',
  `class` varchar(255) NOT NULL DEFAULT '',
  `provider` varchar(255) NOT NULL DEFAULT '',
  `d_update` varchar(255) NOT NULL DEFAULT '',
  `cid` varchar(255) NOT NULL DEFAULT '',
  `cid_aes` varchar(2000) NOT NULL DEFAULT '',
  `log_import_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`hospcode`,`pid`,`seq`,`date_serv`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
