CREATE TABLE `drug_ipd` (
  `hospcode` varchar(10) NOT NULL DEFAULT '',
  `pid` varchar(100) NOT NULL DEFAULT '',
  `an` varchar(100) NOT NULL DEFAULT '',
  `datetime_admit` varchar(100) NOT NULL DEFAULT '',
  `wardstay` varchar(255) NOT NULL DEFAULT '',
  `typedrug` varchar(100) NOT NULL DEFAULT '',
  `didstd` varchar(100) NOT NULL DEFAULT '',
  `dname` varchar(255) NOT NULL DEFAULT '',
  `datestart` varchar(255) NOT NULL DEFAULT '',
  `datefinish` varchar(255) NOT NULL DEFAULT '',
  `amount` varchar(255) NOT NULL DEFAULT '',
  `unit` varchar(255) NOT NULL DEFAULT '',
  `unit_packing` varchar(255) NOT NULL DEFAULT '',
  `drugprice` varchar(255) NOT NULL DEFAULT '',
  `drugcost` varchar(255) NOT NULL DEFAULT '',
  `provider` varchar(255) NOT NULL DEFAULT '',
  `d_update` varchar(255) NOT NULL DEFAULT '',
  `cid` varchar(255) NOT NULL DEFAULT '',
  `cid_aes` varchar(2000) NOT NULL DEFAULT '',
  `log_import_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`hospcode`,`pid`,`an`,`datetime_admit`,`typedrug`,`didstd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
