CREATE TABLE `home` (
  `hospcode` varchar(5) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `hid` varchar(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `house_id` varchar(255) NOT NULL DEFAULT '',
  `housetype` varchar(255) NOT NULL DEFAULT '',
  `roomno` varchar(255) NOT NULL DEFAULT '',
  `condo` varchar(255) NOT NULL DEFAULT '',
  `house` varchar(255) NOT NULL DEFAULT '',
  `soisub` varchar(255) NOT NULL DEFAULT '',
  `soimain` varchar(255) NOT NULL DEFAULT '',
  `road` varchar(255) NOT NULL DEFAULT '',
  `villaname` varchar(255) NOT NULL DEFAULT '',
  `village` varchar(255) NOT NULL DEFAULT '',
  `tambon` varchar(255) NOT NULL DEFAULT '',
  `ampur` varchar(255) NOT NULL DEFAULT '',
  `changwat` varchar(255) NOT NULL DEFAULT '',
  `telephone` varchar(1000) NOT NULL DEFAULT '',
  `latitude` varchar(255) NOT NULL DEFAULT '',
  `longitude` varchar(255) NOT NULL DEFAULT '',
  `nfamily` varchar(255) NOT NULL DEFAULT '',
  `locatype` varchar(255) NOT NULL DEFAULT '',
  `vhvid` varchar(255) NOT NULL DEFAULT '',
  `headid` varchar(255) NOT NULL DEFAULT '',
  `toilet` varchar(255) NOT NULL DEFAULT '',
  `water` varchar(255) NOT NULL DEFAULT '',
  `watertype` varchar(255) NOT NULL DEFAULT '',
  `garbage` varchar(255) NOT NULL DEFAULT '',
  `housing` varchar(255) NOT NULL DEFAULT '',
  `durability` varchar(255) NOT NULL DEFAULT '',
  `cleanliness` varchar(255) NOT NULL DEFAULT '',
  `ventilation` varchar(255) NOT NULL DEFAULT '',
  `light` varchar(255) NOT NULL DEFAULT '',
  `watertm` varchar(255) NOT NULL DEFAULT '',
  `mfood` varchar(255) NOT NULL DEFAULT '',
  `bcontrol` varchar(255) NOT NULL DEFAULT '',
  `acontrol` varchar(255) NOT NULL DEFAULT '',
  `chemical` varchar(255) NOT NULL DEFAULT '',
  `outdate` varchar(255) NOT NULL DEFAULT '',
  `d_update` varchar(255) NOT NULL DEFAULT '',
  `log_import_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`hospcode`,`hid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
