CREATE TABLE `newborn` (
  `hospcode` varchar(5) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `pid` varchar(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `mpid` varchar(255) NOT NULL DEFAULT '',
  `gravida` varchar(255) NOT NULL DEFAULT '',
  `ga` varchar(255) NOT NULL DEFAULT '',
  `bdate` varchar(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `btime` varchar(255) NOT NULL DEFAULT '',
  `bplace` varchar(255) NOT NULL DEFAULT '',
  `bhosp` varchar(255) NOT NULL DEFAULT '',
  `birthno` varchar(255) NOT NULL DEFAULT '',
  `btype` varchar(255) NOT NULL DEFAULT '',
  `bdoctor` varchar(255) NOT NULL DEFAULT '',
  `bweight` varchar(255) NOT NULL DEFAULT '',
  `asphyxia` varchar(255) NOT NULL DEFAULT '',
  `vitk` varchar(255) NOT NULL DEFAULT '',
  `tsh` varchar(255) NOT NULL DEFAULT '',
  `tshresult` varchar(255) NOT NULL DEFAULT '',
  `d_update` varchar(255) NOT NULL DEFAULT '',
  `cid` varchar(255) NOT NULL DEFAULT '',
  `length` varchar(255) NOT NULL DEFAULT '',
  `headcircum` varchar(255) NOT NULL DEFAULT '',
  `cid_aes` varchar(255) NOT NULL DEFAULT '',
  `file_name` varchar(255) NOT NULL DEFAULT '',
  `import_date_time` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`hospcode`,`pid`,`bdate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
