CREATE TABLE `person` (
  `hospcode` varchar(5) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `cid` varchar(255) NOT NULL DEFAULT '',
  `pid` varchar(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `hid` varchar(255) NOT NULL DEFAULT '',
  `prename` varchar(255) NOT NULL DEFAULT '',
  `name` varchar(255) NOT NULL DEFAULT '',
  `lname` varchar(1000) NOT NULL DEFAULT '',
  `hn` varchar(255) NOT NULL DEFAULT '',
  `sex` varchar(255) NOT NULL DEFAULT '',
  `birth` varchar(255) NOT NULL DEFAULT '',
  `mstatus` varchar(255) NOT NULL DEFAULT '',
  `occupation_old` varchar(255) NOT NULL DEFAULT '',
  `occupation_new` varchar(255) NOT NULL DEFAULT '',
  `race` varchar(255) NOT NULL DEFAULT '',
  `nation` varchar(255) NOT NULL DEFAULT '',
  `religion` varchar(255) NOT NULL DEFAULT '',
  `education` varchar(255) NOT NULL DEFAULT '',
  `fstatus` varchar(255) NOT NULL DEFAULT '',
  `father` varchar(255) NOT NULL DEFAULT '',
  `mother` varchar(255) NOT NULL DEFAULT '',
  `couple` varchar(255) NOT NULL DEFAULT '',
  `vstatus` varchar(255) NOT NULL DEFAULT '',
  `movein` varchar(255) NOT NULL DEFAULT '',
  `discharge` varchar(255) NOT NULL DEFAULT '',
  `ddischarge` varchar(255) NOT NULL DEFAULT '',
  `abogroup` varchar(255) NOT NULL DEFAULT '',
  `rhgroup` varchar(255) NOT NULL DEFAULT '',
  `labor` varchar(255) NOT NULL DEFAULT '',
  `passport` varchar(255) NOT NULL DEFAULT '',
  `typearea` varchar(255) NOT NULL DEFAULT '',
  `d_update` varchar(255) NOT NULL DEFAULT '',
  `telephone` varchar(1000) NOT NULL DEFAULT '',
  `mobile` varchar(1000) NOT NULL DEFAULT '',
  `cid_aes` varchar(1000) NOT NULL DEFAULT '',
  `log_import_id` int DEFAULT NULL,
  PRIMARY KEY (`hospcode`,`pid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
