CREATE TABLE `prenatal` (
  `hospcode` varchar(5) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `pid` varchar(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `gravida` varchar(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `lmp` varchar(255) NOT NULL DEFAULT '',
  `edc` varchar(255) NOT NULL DEFAULT '',
  `vdrl_result` varchar(255) NOT NULL DEFAULT '',
  `hb_result` varchar(255) NOT NULL DEFAULT '',
  `hiv_result` varchar(255) NOT NULL DEFAULT '',
  `date_hct` varchar(255) NOT NULL DEFAULT '',
  `hct_result` varchar(255) NOT NULL DEFAULT '',
  `thalassemia` varchar(255) NOT NULL DEFAULT '',
  `d_update` varchar(255) NOT NULL DEFAULT '',
  `provider` varchar(255) NOT NULL DEFAULT '',
  `cid` varchar(255) NOT NULL DEFAULT '',
  `height` varchar(255) NOT NULL DEFAULT '',
  `cid_aes` varchar(255) NOT NULL DEFAULT '',
  `file_name` varchar(255) NOT NULL DEFAULT '',
  `import_date_time` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`hospcode`,`pid`,`gravida`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
