CREATE TABLE `refer_history` (
  `hospcode` varchar(5) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `referid` varchar(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `referid_province` varchar(255) NOT NULL DEFAULT '',
  `pid` varchar(255) NOT NULL DEFAULT '',
  `seq` varchar(255) NOT NULL DEFAULT '',
  `an` varchar(255) NOT NULL DEFAULT '',
  `referid_origin` varchar(255) NOT NULL DEFAULT '',
  `hospcode_origin` varchar(255) NOT NULL DEFAULT '',
  `datetime_serv` varchar(255) NOT NULL DEFAULT '',
  `datetime_admit` varchar(255) NOT NULL DEFAULT '',
  `datetime_refer` varchar(255) NOT NULL DEFAULT '',
  `clinic_refer` varchar(255) NOT NULL DEFAULT '',
  `hosp_destination` varchar(255) NOT NULL DEFAULT '',
  `chiefcomp` varchar(255) NOT NULL DEFAULT '',
  `physicalexam` varchar(255) NOT NULL DEFAULT '',
  `diagfirst` varchar(255) NOT NULL DEFAULT '',
  `diaglast` varchar(255) NOT NULL DEFAULT '',
  `pstatus` varchar(255) NOT NULL DEFAULT '',
  `ptype` varchar(255) NOT NULL DEFAULT '',
  `emergency` varchar(255) NOT NULL DEFAULT '',
  `ptypedis` varchar(255) NOT NULL DEFAULT '',
  `causeout` varchar(255) NOT NULL DEFAULT '',
  `request` varchar(255) NOT NULL DEFAULT '',
  `provider` varchar(255) NOT NULL DEFAULT '',
  `d_update` varchar(255) NOT NULL DEFAULT '',
  `log_import_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`hospcode`,`referid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
