CREATE TABLE `service` (
  `hospcode` varchar(5) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `pid` varchar(255) NOT NULL DEFAULT '',
  `hn` varchar(255) NOT NULL DEFAULT '',
  `seq` varchar(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `date_serv` varchar(8) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `time_serv` varchar(255) NOT NULL DEFAULT '',
  `location` varchar(255) NOT NULL DEFAULT '',
  `intime` varchar(255) NOT NULL DEFAULT '',
  `instype` varchar(255) NOT NULL DEFAULT '',
  `insid` varchar(2000) NOT NULL DEFAULT '',
  `main` varchar(255) NOT NULL DEFAULT '',
  `typein` varchar(255) NOT NULL DEFAULT '',
  `referinhosp` varchar(255) NOT NULL DEFAULT '',
  `causein` varchar(255) NOT NULL DEFAULT '',
  `chiefcomp` varchar(255) NOT NULL DEFAULT '',
  `servplace` varchar(255) NOT NULL DEFAULT '',
  `btemp` varchar(255) NOT NULL DEFAULT '',
  `sbp` varchar(255) NOT NULL DEFAULT '',
  `dbp` varchar(255) NOT NULL DEFAULT '',
  `pr` varchar(255) NOT NULL DEFAULT '',
  `rr` varchar(255) NOT NULL DEFAULT '',
  `typeout` varchar(255) NOT NULL DEFAULT '',
  `referouthosp` varchar(255) NOT NULL DEFAULT '',
  `causeout` varchar(255) NOT NULL DEFAULT '',
  `cost` varchar(255) NOT NULL DEFAULT '',
  `price` varchar(255) NOT NULL DEFAULT '',
  `payprice` varchar(255) NOT NULL DEFAULT '',
  `actualpay` varchar(255) NOT NULL DEFAULT '',
  `d_update` varchar(255) NOT NULL DEFAULT '',
  `hsub` varchar(255) NOT NULL DEFAULT '',
  `cid` varchar(255) NOT NULL DEFAULT '',
  `cid_aes` varchar(2000) NOT NULL DEFAULT '',
  `log_import_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`hospcode`,`seq`,`date_serv`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
