CREATE TABLE `surveillance` (
  `hospcode` varchar(5) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `pid` varchar(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `seq` varchar(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `date_serv` varchar(8) NOT NULL DEFAULT '',
  `an` varchar(255) NOT NULL DEFAULT '',
  `datetime_admit` varchar(255) NOT NULL DEFAULT '',
  `syndrome` varchar(255) NOT NULL DEFAULT '',
  `diagcode` varchar(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `code506` varchar(255) NOT NULL DEFAULT '',
  `diagcodelast` varchar(255) NOT NULL DEFAULT '',
  `code506last` varchar(255) NOT NULL DEFAULT '',
  `illdate` varchar(255) NOT NULL DEFAULT '',
  `illhouse` varchar(255) NOT NULL DEFAULT '',
  `illvillage` varchar(255) NOT NULL DEFAULT '',
  `illtambon` varchar(255) NOT NULL DEFAULT '',
  `illampur` varchar(255) NOT NULL DEFAULT '',
  `illchangwat` varchar(255) NOT NULL DEFAULT '',
  `latitude` varchar(255) NOT NULL DEFAULT '',
  `longitude` varchar(255) NOT NULL DEFAULT '',
  `ptstatus` varchar(255) NOT NULL DEFAULT '',
  `date_death` varchar(255) NOT NULL DEFAULT '',
  `complication` varchar(255) NOT NULL DEFAULT '',
  `organism` varchar(255) NOT NULL DEFAULT '',
  `provider` varchar(255) NOT NULL DEFAULT '',
  `d_update` varchar(255) NOT NULL DEFAULT '',
  `cid` varchar(255) NOT NULL DEFAULT '',
  `cid_aes` varchar(255) NOT NULL DEFAULT '',
  `file_name` varchar(255) NOT NULL DEFAULT '',
  `import_date_time` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`hospcode`,`pid`,`seq`,`diagcode`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
