CREATE TABLE `village` (
  `hospcode` varchar(5) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `vid` varchar(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `ntraditional` varchar(255) NOT NULL DEFAULT '',
  `nmonk` varchar(255) NOT NULL DEFAULT '',
  `nreligionleader` varchar(255) NOT NULL DEFAULT '',
  `nbroadcast` varchar(255) NOT NULL DEFAULT '',
  `nradio` varchar(255) NOT NULL DEFAULT '',
  `npchc` varchar(255) NOT NULL DEFAULT '',
  `nclinic` varchar(255) NOT NULL DEFAULT '',
  `ndrugstore` varchar(255) NOT NULL DEFAULT '',
  `nchildcenter` varchar(255) NOT NULL DEFAULT '',
  `npschool` varchar(255) NOT NULL DEFAULT '',
  `nsschool` varchar(255) NOT NULL DEFAULT '',
  `ntemple` varchar(255) NOT NULL DEFAULT '',
  `nreligiousplace` varchar(255) NOT NULL DEFAULT '',
  `nmarket` varchar(255) NOT NULL DEFAULT '',
  `nshop` varchar(255) NOT NULL DEFAULT '',
  `nfoodshop` varchar(255) NOT NULL DEFAULT '',
  `nstall` varchar(255) NOT NULL DEFAULT '',
  `nraintank` varchar(255) NOT NULL DEFAULT '',
  `nchickenfarm` varchar(255) NOT NULL DEFAULT '',
  `npigfarm` varchar(255) NOT NULL DEFAULT '',
  `wastewater` varchar(255) NOT NULL DEFAULT '',
  `garbage` varchar(255) NOT NULL DEFAULT '',
  `nfactory` varchar(255) NOT NULL DEFAULT '',
  `latitude` varchar(255) NOT NULL DEFAULT '',
  `longitude` varchar(255) NOT NULL DEFAULT '',
  `outdate` varchar(255) NOT NULL DEFAULT '',
  `numactually` varchar(255) NOT NULL DEFAULT '',
  `risktype` varchar(255) NOT NULL DEFAULT '',
  `numstateless` varchar(255) NOT NULL DEFAULT '',
  `nexerciseclub` varchar(255) NOT NULL DEFAULT '',
  `nolderlyclub` varchar(255) NOT NULL DEFAULT '',
  `ndisableclub` varchar(255) NOT NULL DEFAULT '',
  `nnumberoneclub` varchar(255) NOT NULL DEFAULT '',
  `d_update` varchar(255) NOT NULL DEFAULT '',
  `log_import_id` int DEFAULT NULL,
  PRIMARY KEY (`hospcode`,`vid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
